/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frm;

import database_conf.connectDB;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author mhieu
 */
public class timkiem extends javax.swing.JFrame {

    /**
     * Creates new form timkiem
     */
    
    private int masp;
    private String tensp;
    
    private final connectDB db = new connectDB();
    private final Connection conn = db.connect();
    
    private PreparedStatement stmt;
    public timkiem() {
        initComponents();
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Tìm kiếm sản phẩm");

        jLabel2.setText("Mã Sản Phẩm ");

        jTextField1.setText("jTextField1");

        jLabel3.setText("Tên sản phẩm");

        jTextField2.setText("jTextField2");

        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Reset");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Mã sp", "Tên sp", "Giá nhập", "Giá bán", "Ngày nhập", "Tồn kho "
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(225, 225, 225))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(235, 235, 235)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 569, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(57, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        jTextField1.setText("");
        jTextField2.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        if(!jTextField1.getText().equals("") && jTextField2.getText().equals("")) {
            masp = Integer.valueOf(jTextField1.getText());
            System.out.println("Ten:" + masp);
            String query = "SELECT sp.masp, sp.tensp, sp.gianhap, sp.giaban, sp.tonkho FROM sanpham as sp "
                   + "WHERE masp = ?";
            
            try {
                stmt = conn.prepareStatement(query);
                stmt.setInt(1, masp);
                
                ResultSet rs = stmt.executeQuery();
                
                Object[] obj = 
                    new Object[] {"masp", "tensp", "gianhap", "giaban","tonkho"};
                
                DefaultTableModel tableModel = new DefaultTableModel(obj, 0);
                jTable1.setModel(tableModel);
                while(rs.next()) {
                    Object[] item = new Object[5];
                    
                    item[0] = rs.getInt("masp");
                    item[1] = rs.getString("tensp");
                    item[2] = rs.getInt("gianhap");
                    item[3] = rs.getInt("giaban");
                    item[4] = rs.getInt("tonkho");
                    
                    tableModel.addRow(item);
                }
                
            } catch (SQLException ex) {
                Logger.getLogger(timkiem.class.getName()).log(Level.SEVERE, null, ex);
            }
               
        } else if(jTextField1.getText().equals("") && !jTextField2.getText().equals("")) {
            tensp = "%" + jTextField2.getText() +"%";
            
            String query = "SELECT sp.masp, sp.tensp, sp.gianhap, sp.giaban, sp.tonkho FROM sanpham as sp "
                   + "WHERE lower(tensp) LIKE ?";
            
            try {
                stmt = conn.prepareStatement(query);
                stmt.setString(1, tensp);
                
                ResultSet rs = stmt.executeQuery();
                
                Object[] obj = 
                    new Object[] {"masp", "tensp", "gianhap", "giaban","tonkho"};
                
                DefaultTableModel tableModel = new DefaultTableModel(obj, 0);
                jTable1.setModel(tableModel);
                while(rs.next()) {
                    Object[] item = new Object[5];
                    
                    item[0] = rs.getInt("masp");
                    item[1] = rs.getString("tensp");
                    item[2] = rs.getInt("gianhap");
                    item[3] = rs.getInt("giaban");
                    item[4] = rs.getInt("tonkho");
                    
                    tableModel.addRow(item);
                }
                
            } catch (SQLException ex) {
                Logger.getLogger(timkiem.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else if(jTextField1.getText().equals("") && jTextField2.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Ban chua nhap gi");
        } else if(!jTextField1.getText().equals("") && !jTextField2.getText().equals("")) {
            masp = Integer.valueOf(jTextField1.getText());
            tensp = "%" + jTextField2.getText() +"%";
            
            String query = "SELECT sp.masp, sp.tensp, sp.gianhap, sp.giaban, sp.tonkho FROM sanpham as sp "
                   + "WHERE lower(tensp) LIKE ? AND masp = ?";
            
            try {
                stmt = conn.prepareStatement(query);
                stmt.setString(1, tensp);
                stmt.setInt(2, masp);
                ResultSet rs = stmt.executeQuery();
                
                Object[] obj = 
                    new Object[] {"masp", "tensp", "gianhap", "giaban","tonkho"};
                
                DefaultTableModel tableModel = new DefaultTableModel(obj, 0);
                jTable1.setModel(tableModel);
                while(rs.next()) {
                    Object[] item = new Object[5];
                    
                    item[0] = rs.getInt("masp");
                    item[1] = rs.getString("tensp");
                    item[2] = rs.getInt("gianhap");
                    item[3] = rs.getInt("giaban");
                    item[4] = rs.getInt("tonkho");
                    
                    tableModel.addRow(item);
                }
                
            } catch (SQLException ex) {
                Logger.getLogger(timkiem.class.getName()).log(Level.SEVERE, null, ex);
            }
        } 
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(timkiem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(timkiem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(timkiem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(timkiem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new timkiem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
